version: '3.3'
services:
     nginx:
#        image: nginxapp
        container_name: nginxapp
        build:
          context: ./nginx_serv/
        restart: always
        ports:
         - '80:80'
        volumes:
              - ./nginx_serv/nginx_conf/conf.d:/etc/nginx/conf.d
              - ./nginx_serv/app/:/var/www/html/
              - ./nginx_serv/log/:/var/log/nginx/     
        networks: 
            - main-server_docker-bridged

       
      
     php_fpm:
#      image: php_fpm
       container_name: php_fpm
       build:
         context: ./php_fpm_serv/
       restart: always
       ports:
         - '9000:9000'
       volumes:
          - ./php_fpm_serv/app/:/var/www/html/
#         - ./nginx_serv/app/:/var/www/html/  
       networks:
           - main-server_docker-bridged

     db: 
       image: mysql
       container_name: mysql 
       command: --default-authentication-plugin=mysql_native_password 
       restart: always 
       ports:
         - '3306:3306'
       environment: 
          MYSQL_ROOT_PASSWORD: TestSkuljoba2024!
    
       networks:
          - main-server_docker-bridged 


     phpmyadmin: 
       image: phpmyadmin
       container_name: phpmyadmin 
       restart: always 
       ports: 
         - 8080:8080
       environment: 
         - PMA_ARBITRARY=1
         - APACHE_HTTP_PORT_NUMBER=8080
       command: /bin/bash -c "sed -i \"s/80/$$APACHE_HTTP_PORT_NUMBER/g\" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf && /docker-entrypoint.sh apache2-foreground"
       networks:
          - main-server_docker-bridged
networks:
  main-server_docker-bridged:
     driver: bridge
